#!/usr/bin/env python3
""" Factor numbers """
from sys import argv
from math import sqrt

def open_and_read_file(file_name):
    """read from a file add to array"""
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
        number_to_factor = []
        for i in lines:
            number_to_factor.append(int(i))
            return number_to_factor

        def find_and_times(n):
            """factor each n given"""
            for i in range(1, n):
                if n == ((n // i) * i):
                    print("{}={}*{}".format(n, (n // i), i))
                    break
                
                def factor_list(list):
                    """factor each num in list"""
                    for i in list:
                        find_and_times(i)

                        if len(argv) == 2:
                            factor_list(open_and_read_file(argv[1]))
